# Generated by Django 5.0.6 on 2026-08-11 21:30

from django.db import migrations, models


def rename_unspecified_to_prefer_not_to_say(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(gender="unspecified").update(gender="prefer_not_to_say")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20),
        ),
        migrations.RunPython(rename_unspecified_to_prefer_not_to_say, migrations.RunPython.noop),
    ]
