# Generated by Django 5.0.6 on 2026-07-15 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/albums/')),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('release_year', models.PositiveSmallIntegerField()),
                ('release_type', models.CharField(choices=[('single', 'Single'), ('album', 'Album')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='accounts.artistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='tracks/audio/')),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('track_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_tracks', to='accounts.artistprofile')),
            ],
            options={
                'ordering': ['album_id', 'track_number'],
            },
        ),
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to='music.track')),
            ],
            options={
                'indexes': [models.Index(fields=['track', 'user'], name='music_strea_track_i_9174ad_idx')],
            },
        ),
    ]
