# Generated by Django 5.0.6 on 2026-07-15 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='en', max_length=8)),
                ('system_volume', models.PositiveSmallIntegerField(default=80)),
                ('notify_new_releases', models.BooleanField(default=True)),
                ('notify_subscription', models.BooleanField(default=True)),
                ('notify_artist_verification', models.BooleanField(default=True)),
                ('notify_tickets', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
