# Generated by Django 5.0.6 on 2026-07-15 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=16, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_stream_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('playlist_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('can_upload_profile_photo', models.BooleanField(default=False)),
                ('can_download_tracks', models.BooleanField(default=False)),
                ('early_access_to_releases', models.BooleanField(default=False)),
                ('can_view_artist_stats', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.PositiveSmallIntegerField(choices=[(1, 'One Month'), (3, 'Three Months'), (6, 'Six Months'), (12, 'Twelve Months')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('zarinpal', 'ZarinPal'), ('aqayepardakht', 'AqayePardakht'), ('payping', 'PayPing'), ('sizpay', 'SizPay')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('gateway_ref_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(help_text='First day of the settlement month')),
                ('unique_listeners', models.PositiveIntegerField(default=0)),
                ('total_streams', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending settlement'), ('paid', 'Paid')], default='pending', max_length=16)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='accounts.artistprofile')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_month'],
                'unique_together': {('artist_profile', 'period_month')},
            },
        ),
    ]
