# Generated by Django 5.0.6 on 2026-08-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='duration_months',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'One Month'), (3, 'Three Months'), (6, 'Six Months'), (12, 'Twelve Months')], null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='plan_tier',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=16),
        ),
    ]
